pool:
    name: Automation_Playground
    demands:
    - agent.name -equals LinuxTDC

steps:
    - script: bash greeting.sh
      displayName: '打招呼'
    - script: python3 month.py
      displayName: '顯示月曆'
       